In [13]:
import pandas as pd

word = pd.read_csv('word.csv').drop(columns=['Unnamed: 0'])
word = pd.concat(g for _, g in word.groupby("Group"))
word[:10]

,Cantonese,Part of Speech,Group,English,Pronunciation,Sentence1,Meaning1,Jyutping1,Sentence2,Meaning2,Jyutping2,Sentence3,Meaning3,Jyutping3,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,Unnamed: 0.1.1.1.1
39,班,Noun,Academics,class,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,堂,Noun,Academics,lesson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,書檯,Noun,Academics,desk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,功課,Noun,Academics,"homework, assignment",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,校長,Noun,Academics,principal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,成績表,Noun,Academics,"transcript, report card",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,學期,Noun,Academics,"term, semester",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,學生,Noun,Academics,student,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,老師,Noun,Academics,teacher,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,畢業,Verb,Academics,to graduate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
duplicate = pd.concat(g for _, g in word.groupby(["Cantonese", "Part of Speech"]) if len(g) > 1)
duplicate.to_csv('duplicate.csv')

In [16]:
duplicate = pd.read_csv('duplicate.csv')
word = word.drop_duplicates(subset=["Cantonese", "Part of Speech"], keep=False).append(duplicate)
word

,Cantonese,Part of Speech,Group,English,Pronunciation,Sentence1,Meaning1,Jyutping1,Sentence2,Meaning2,Jyutping2,Sentence3,Meaning3,Jyutping3,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,Unnamed: 0.1.1.1.1,Unnamed: 0
39,班,Noun,Academics,class,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,堂,Noun,Academics,lesson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,書檯,Noun,Academics,desk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,功課,Noun,Academics,"homework, assignment",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,校長,Noun,Academics,principal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22,雞,Noun,Animals,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.0
23,雞,Noun,Food and drink,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,424.0
24,電視,Noun,Daily Objects,TV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,151.0
25,飛,Noun,"Movies, TV, and Radio",ticket,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,548.0
26,魚,Noun,Animals,fish,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.0

In [17]:
word.to_csv('word.csv')

In [2]:
import pycantonese
import pandas as pd

word = pd.read_csv('word.csv').drop(columns=['Sentence1', 'Meaning1', 'Jyutping1', 'Sentence2', 'Meaning2', 'Jyutping2', 'Sentence3', 'Meaning3', 'Jyutping3', 'Unnamed: 0.1', 'Unnamed: 0.1.1', 'Unnamed: 0.1.1.1', 'Unnamed: 0.1.1.1.1', 'Unnamed: 0', 'Unnamed: 0.1.1.1.1.1'])

word

,Cantonese,Part of Speech,Group,English,Pronunciation
0,班,Noun,Academics,class,NaN
1,堂,Noun,Academics,lesson,NaN
2,書檯,Noun,Academics,desk,NaN
3,功課,Noun,Academics,"homework, assignment",NaN
4,校長,Noun,Academics,principal,NaN
...,...,...,...,...,...
693,雞,Noun,Animals,chicken,NaN
694,雞,Noun,Food and drink,chicken,NaN
695,電視,Noun,Daily Objects,TV,NaN
696,飛,Noun,"Movies, TV, and Radio",ticket,NaN
697,魚,Noun,Animals,fish,NaN

In [3]:
import numpy as np
import re

for i in range(word.shape[0]):
    if pd.isnull(word.iloc[i][4]):
        word.iloc[i][4] = pycantonese.characters_to_jyutping(word.iloc[i][0])[0][1]
    else: 
        word.iloc[i][4] = re.sub('\s', '', word.iloc[i][4])

word

,Cantonese,Part of Speech,Group,English,Pronunciation
0,班,Noun,Academics,class,baan1
1,堂,Noun,Academics,lesson,tong4
2,書檯,Noun,Academics,desk,syu1toi2
3,功課,Noun,Academics,"homework, assignment",gung1fo3
4,校長,Noun,Academics,principal,haau6zoeng2
...,...,...,...,...,...
693,雞,Noun,Animals,chicken,gai1
694,雞,Noun,Food and drink,chicken,gai1
695,電視,Noun,Daily Objects,TV,din6si6
696,飛,Noun,"Movies, TV, and Radio",ticket,fei1
697,魚,Noun,Animals,fish,jyu2

In [4]:
word.to_csv('word.csv')